import type { Metadata } from "next";
import { Barlow, Exo_2, VT323 } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/provider/tanstack-provider";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/user";
import { MatchProvider } from "@/context/match";

// Import font từ Google với weight
const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const vt323 = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <MatchProvider>
        <UserProvider>
          <html lang="en">
            <body
              className={`${barlow.variable} ${exo2.variable} ${vt323.variable} antialiased bg-black`}
            >
              {children}
              <Toaster
                position="top-center"
                toastOptions={{
                  duration: 3000,
                  style: {
                    background: "#0a0a0a",
                    color: "#e5e5e5",
                    border: "1px solid #00ff5c",
                    boxShadow: "0 0 15px #00ff5c55",
                    fontFamily: "var(--font-exo2), sans-serif",
                  },
                  success: {
                    style: {
                      border: "1px solid #00ff5c",
                      color: "#00ff5c",
                      boxShadow: "0 0 20px #00ff5c88",
                    },
                    iconTheme: {
                      primary: "#00ff5c",
                      secondary: "#0a0a0a",
                    },
                  },
                  error: {
                    style: {
                      border: "1px solid #ff005c",
                      color: "#ff005c",
                      boxShadow: "0 0 20px #ff005c88",
                    },
                    iconTheme: {
                      primary: "#ff005c",
                      secondary: "#0a0a0a",
                    },
                  },
                }}
              />
            </body>
          </html>
        </UserProvider>
      </MatchProvider>
    </QueryProvider>
  );
}
